import { PyEOConfig } from "@/types/config";
import { CLASS_LABELS } from "@/constants/options";

/**
 * Generate a UUID v4 string
 */
export function generateUUID(): string {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Format a date string (YYYY-MM-DD) to INI format (YYYYMMDD)
 */
export function formatDateForIni(dateString: string): string {
  return dateString.replace(/-/g, "");
}

/**
 * Convert JS boolean to Python boolean string
 */
function pyBool(val: boolean): string {
  return val ? "True" : "False";
}

/**
 * Generate a complete PyEO .ini configuration file
 */
export function generateIniFile(config: PyEOConfig): string {
  return `# PyEO Configuration File
# Generated by PyEO Config UI
# UUID: ${config.uuid}
# Project: ${config.projectName}
# Generated: ${new Date().toISOString()}

[run_mode]
do_parallel = False
wall_time_hours = 3
watch_time_hours = 3
watch_period_seconds = 60

[forest_sentinel]
# Project: ${config.projectName}
start_date=${formatDateForIni(config.startDate)}
end_date=${formatDateForIni(config.endDate)}
composite_start=${formatDateForIni(config.compositeStart)}
composite_end=${formatDateForIni(config.compositeEnd)}
epsg=${config.epsg}
cloud_cover=${config.cloudCover}
cloud_certainty_threshold=0
model=${config.modelPath}

[environment]
# UPDATE THESE PATHS FOR YOUR SYSTEM
pyeo_dir = C:\\Users\\YOUR_USERNAME\\pyeo
tile_dir = C:\\Users\\YOUR_USERNAME\\pyeo_data
integrated_dir = .\\integrated
roi_dir = .\\roi
roi_filename = ${config.roiFilename}
geometry_dir = .\\geometry
log_dir = .\\log
credentials_path = .\\credentials\\credentials.ini
environment_manager = conda
conda_env_name = pyeo_env

[raster_processing_parameters]
do_tile_intersection = True
do_raster = True
chunks = 10
do_skip_existing = True
do_quicklooks = False
do_delete = False
download_source = ${config.downloadSource}
faulty_granule_threshold = 350
band_names = ["B02", "B03", "B04", "B08"]
resolution_string = "10m"
output_resolution = 10

# Processing Steps
do_build_composite = ${pyBool(config.doBuildComposite)}
buffer_size_cloud_masking_composite = 10
download_limit = 10

do_download = ${pyBool(config.doDownload)}
buffer_size_cloud_masking = 20

do_classify = ${pyBool(config.doClassify)}
class_labels = ${JSON.stringify(CLASS_LABELS)}
sieve = 0

do_change = ${pyBool(config.doChange)}
change_from_classes = [${config.changeFromClasses.join(", ")}]
change_to_classes = [${config.changeToClasses.join(", ")}]

[vector_processing_parameters]
do_delete_existing_vector = True
do_vectorise = ${pyBool(config.doVectorise)}
do_integrate = True
do_filter = False
minimum_area_to_report_m2 = 120
do_distribution = False
`;
}

/**
 * Download the config as an .ini file
 */
export function downloadIniFile(config: PyEOConfig): void {
  const iniContent = generateIniFile(config);
  const blob = new Blob([iniContent], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `pyeo_${config.projectName.toLowerCase().replace(/\s+/g, "_")}.ini`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy the config to clipboard
 */
export async function copyIniToClipboard(config: PyEOConfig): Promise<void> {
  const iniContent = generateIniFile(config);
  await navigator.clipboard.writeText(iniContent);
}